server:
  address: "0.0.0.0"
  port: "80"
placesApi:
  host: http://go-explore.ru/proxy/maps/api/
logger:
  format: plain
  level: 4
  name: suggest
  output: ./log/sugest.log
categories:
  - amusement_park
  - aquarium
#  - art_gallery
#  - bar
  - mosque
#  - movie_theater
#  - bowling_alley
  - museum
#  - cafe
#  - night_club
  - park
#  - casino
  - church
  - city_hall
#  - restaurant
#  - shopping_mall
  - stadium
  - synagogue
  - tourist_attraction
  - hindu_temple
  - zoo